# --- COMPREHENSIVE I18N DICTIONARY ---
LANGUAGES = {
    'English': {
        'settings': 'Settings',
        'upload_msg': 'Upload B3 Statements (XLSX)',
        'welcome_msg': '💡 Welcome! Please upload your B3 statement files in the sidebar.',
        'fetching_prices': 'Fetching market prices...',
        'total_invested': 'Total Invested',
        'market_value': 'Market Value',
        'gross_pnl': 'Gross P&L',
        'total_earnings': 'Total Earnings',
        'allocation_title': 'Allocation by Category',
        'earnings_title': 'Top Earnings by Ticker',
        'detailed_title': 'Detailed Portfolio Position',
        'download_btn': '📥 Download Consolidated Excel',
        # Table Headers
        'col_ticker': 'Ticker',
        'col_category': 'Category',
        'col_qty': 'Quantity',
        'col_avg_price': 'Avg Price',
        'col_total_cost': 'Total Cost',
        'col_earnings': 'Earnings',
        'col_curr_price': 'Current Price',
        'col_yield': 'Yield (%)',
        'col_pnl': 'P&L (Realized/Unrealized)',
        # Categories
        'cat_treasury': 'Treasury Bonds',
        'cat_reits': 'REITs (FIIs)',
        'cat_stocks': 'Stocks',
        'cat_fixed': 'Fixed Income',
        'cat_others': 'ETFs/Units',
        'warning_duplicate': '⚠️ No new data detected. This file has already been processed.',
    },
    'Português (Brasil)': {
        'settings': 'Configurações',
        'upload_msg': 'Subir Extratos B3 (XLSX)',
        'welcome_msg': '💡 Bem-vindo! Por favor, suba seus extratos da B3 na barra lateral.',
        'fetching_prices': 'Buscando preços de mercado...',
        'total_invested': 'Total Investido',
        'market_value': 'Valor de Mercado',
        'gross_pnl': 'Lucro/Prejuízo Bruto',
        'total_earnings': 'Total de Proventos',
        'allocation_title': 'Alocação por Categoria',
        'earnings_title': 'Maiores Proventos por Ticker',
        'detailed_title': 'Posição Detalhada da Carteira',
        'download_btn': '📥 Baixar Excel Consolidado',
        # Cabeçalhos da Tabela
        'col_ticker': 'Ticker',
        'col_category': 'Categoria',
        'col_qty': 'Quantidade',
        'col_avg_price': 'Preço Médio',
        'col_total_cost': 'Custo Total',
        'col_earnings': 'Proventos',
        'col_curr_price': 'Preço Atual',
        'col_yield': 'Rentabilidade (%)',
        'col_pnl': 'Lucro/Prejuízo',
        # Categorias
        'cat_treasury': 'Tesouro Direto',
        'cat_reits': 'FIIs',
        'cat_stocks': 'Ações',
        'cat_fixed': 'Renda Fixa',
        'cat_others': 'ETFs/Units',
        'warning_duplicate': '⚠️ Nenhum dado novo detectado. Este arquivo já foi processado.',
    }
}
