LANGUAGES = {
    'English': {
        'settings': 'Settings',
        'upload_msg': 'Import B3 Statements (XLSX)',
        'welcome_msg': 'Ready to track your wealth journey?',
        'welcome_sub': '💡 Please upload your B3 files in the sidebar to begin.',
        'fetching_prices': 'Updating live prices...',
        'total_invested': 'Total Invested',
        'market_value': 'Portfolio Value',
        'gross_pnl': 'Total Profit/Loss',
        'total_earnings': 'Passive Income',
        'allocation_title': 'Portfolio Mix',
        'earnings_title': 'Best Income Sources',
        'evolution_title': 'Wealth Evolution',
        'monthly_earnings_title': 'Monthly Income',
        'detailed_title': 'Asset Detail Breakdown',
        'warning_duplicate': '⚠️ Data already up to date.',
        'currency_label': 'Display Currency',
        'exchange_rate_msg': 'Market Rate',
        'status_loaded': '✅ Data loaded',
        'tab_visuals': 'Dashboard',
        'tab_data': 'Data Lab',
        'step_1': '**Step 1**\n\nExport your statements from the [B3 Investor Portal](https://www.investidor.b3.com.br/login).',
        'step_2': '**Step 2**\n\nUpload the files in the sidebar menu.',
        'step_3': '**Step 3**\n\nAnalyze your evolution and cash flow!',
        'col_ticker': 'Asset',
        'col_category': 'Type',
        'col_qty': 'Shares',
        'col_avg_price': 'Paid Price',
        'col_total_cost': 'Invested',
        'col_earnings': 'Dividends',
        'col_curr_price': 'Live Price',
        'col_yield': 'Return',
        'col_pnl': 'Net Result',
        'cat_treasury': 'Bonds',
        'cat_reits': 'REITs',
        'cat_stocks': 'Stocks',
        'cat_fixed': 'Fixed Income',
        'cat_others': 'Others'
    },
    'Português (Brasil)': {
        'settings': 'Configurações',
        'upload_msg': 'Importar Extratos B3 (XLSX)',
        'welcome_msg': 'Pronto para acompanhar sua jornada?',
        'welcome_sub': '💡 Por favor, faça o upload dos seus arquivos da B3 na barra lateral.',
        'fetching_prices': 'Atualizando cotações...',
        'total_invested': 'Total Investido',
        'market_value': 'Patrimônio Atual',
        'gross_pnl': 'Lucro/Prejuízo Total',
        'total_earnings': 'Renda Passiva',
        'allocation_title': 'Composição da Carteira',
        'earnings_title': 'Maiores Pagadores',
        'evolution_title': 'Evolução Patrimonial',
        'monthly_earnings_title': 'Renda Mensal',
        'detailed_title': 'Detalhamento por Ativo',
        'warning_duplicate': '⚠️ Dados já processados.',
        'currency_label': 'Moeda de Exibição',
        'exchange_rate_msg': 'Cotação Mercado',
        'status_loaded': '✅ Dados carregados',
        'tab_visuals': 'Painel Visual',
        'tab_data': 'Laboratório de Dados',
        'step_1': '**Passo 1**\n\nExporte seus extratos no [Portal do Investidor B3](https://www.investidor.b3.com.br/login).',
        'step_2': '**Passo 2**\n\nFaça o upload dos arquivos no menu lateral.',
        'step_3': '**Passo 3**\n\nAcompanhe sua evolução e proventos!',
        'col_ticker': 'Ativo',
        'col_category': 'Tipo',
        'col_qty': 'Qtd',
        'col_avg_price': 'Preço Médio',
        'col_total_cost': 'Investido',
        'col_earnings': 'Dividendos',
        'col_curr_price': 'Cotação Atual',
        'col_yield': 'Rent.',
        'col_pnl': 'Resultado',
        'cat_treasury': 'Tesouro',
        'cat_reits': 'FIIs',
        'cat_stocks': 'Ações',
        'cat_fixed': 'Renda Fixa',
        'cat_others': 'Outros'
    }
}
