LANGUAGES = {
    'English': {
        'upload_msg': 'Import B3 Negotiation Statements (XLSX)',
        'welcome_msg': 'Ready to track your wealth journey?',
        'welcome_sub': '💡 Please upload your B3 Negotiation files in the sidebar.',
        'total_invested': 'Total Invested',
        'market_value': 'Portfolio Value',
        'gross_pnl': 'Total Profit/Loss',
        'currency_label': 'Display Currency',
        'exchange_rate_msg': 'USD Exchange Rate',
        'tab_visuals': 'Dashboard',
        'tab_data': 'Data Lab',
        'chart_evolution': 'Wealth Evolution (Invested Capital)',
        'chart_allocation': 'Allocation by Asset Type',
        'col_ticker': 'Asset',
        'col_type': 'Type',
        'col_qty': 'Shares',
        'col_avg_price': 'Avg Price',
        'col_total_cost': 'Invested',
        'col_curr_price': 'Live Price',
        'col_yield': 'Return',
        'col_pnl': 'Net Result',
        'col_status': 'Status',
        'status_legend': '💡 ✅ Live Price | ⚠️ Using Average Cost.'
    },
    'Português (Brasil)': {
        'upload_msg': 'Importar Notas de Negociação B3 (XLSX)',
        'welcome_msg': 'Pronto para acompanhar sua jornada?',
        'welcome_sub': '💡 Por favor, faça o upload dos seus arquivos de Negociação na barra lateral.',
        'total_invested': 'Total Investido',
        'market_value': 'Patrimônio Atual',
        'gross_pnl': 'Lucro/Prejuízo Total',
        'currency_label': 'Moeda de Exibição',
        'exchange_rate_msg': 'Cotação Mercado',
        'tab_visuals': 'Painel Visual',
        'tab_data': 'Laboratório de Dados',
        'chart_evolution': 'Evolução Patrimonial (Capital Investido)',
        'chart_allocation': 'Alocação por Tipo de Ativo',
        'col_ticker': 'Ativo',
        'col_type': 'Tipo',
        'col_qty': 'Qtd',
        'col_avg_price': 'Preço Médio',
        'col_total_cost': 'Investido',
        'col_curr_price': 'Cotação Atual',
        'col_yield': 'Rent.',
        'col_pnl': 'Resultado',
        'col_status': 'Status',
        'status_legend': '💡 ✅ Preço Real | ⚠️ Usando Preço Médio.'
    }
}
